version: '3.8'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

volumes:
  mysql-data:
# Commenting out sensitive values
# SPRING_DATASOURCE_URL=jdbc:mysql://mysql-a080703-clubworldcup25.c.aivencloud.com:26977/clubworldcup?useSSL=false
# SPRING_DATASOURCE_USERNAME=avnadmin
# SPRING_DATASOURCE_PASSWORD=AVNS_dGqsiIXcDA6R84QpNgU
# SPRING_JPA_HIBERNATE_DDL_AUTO=update
# SPRING_JPA_SHOW_SQL=true
