version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: Localmysql
    environment:
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_DATABASE: clubworldcup
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Localmysql:3306/clubworldcup?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root2

volumes:
  mysql-data:
